"""The 'top 25' VRF issues, as catalog entries.

This is the master list. Each entry has a stable ``rule_id`` and declares which
signals it needs. Detectors in ``detectors.py`` register against these ids; the
``implemented`` flag is set to True automatically for those that have a detector,
so the UI can show coverage (which of the 25 are live vs. planned).
"""

from __future__ import annotations

from .base import RuleSpec, Severity

CATALOG: list[RuleSpec] = [
    RuleSpec("R01_undercharge", "Refrigerant undercharge", "Refrigerant",
             "Low subcooling with high superheat indicates too little refrigerant.",
             ["subcool", "superheat", "low_pressure"], Severity.HIGH),
    RuleSpec("R02_overcharge", "Refrigerant overcharge", "Refrigerant",
             "High subcooling and high head pressure indicate excess charge.",
             ["subcool", "high_pressure", "discharge_temp"], Severity.MEDIUM),
    RuleSpec("R03_leak_trend", "Refrigerant leak (slow trend)", "Refrigerant",
             "Gradual multi-day drift in subcooling/pressures suggests a leak.",
             ["subcool", "high_pressure", "low_pressure"], Severity.HIGH),
    RuleSpec("R04_high_discharge", "High discharge temperature (TH4)", "Compressor",
             "Sustained high compressor discharge temperature risks damage.",
             ["discharge_temp"], Severity.HIGH),
    RuleSpec("R05_hp_trip_risk", "High-pressure trip risk", "Pressure",
             "High side approaching the high-pressure cutout.",
             ["high_pressure"], Severity.HIGH),
    RuleSpec("R06_lp_trip_risk", "Low-pressure trip risk", "Pressure",
             "Low side approaching the low-pressure cutout.",
             ["low_pressure"], Severity.MEDIUM),
    RuleSpec("R07_lev_fault", "LEV (expansion valve) stuck/erratic", "Valves",
             "Superheat decoupled from expansion-valve movement.",
             ["superheat", "lev_pulse"], Severity.MEDIUM),
    RuleSpec("R08_short_cycling", "Compressor short-cycling", "Compressor",
             "Compressor turning on/off too frequently.",
             ["comp_freq"], Severity.MEDIUM),
    RuleSpec("R09_excess_defrost", "Excessive defrost cycles", "Heating",
             "Defrost frequency high relative to ambient conditions.",
             ["defrost", "outdoor_temp"], Severity.LOW),
    RuleSpec("R10_dirty_condenser", "Dirty/blocked condenser", "Airflow",
             "Condensing temperature elevated above ambient.",
             ["cond_temp", "outdoor_temp", "high_pressure"], Severity.MEDIUM),
    RuleSpec("R11_low_indoor_airflow", "Dirty filter / low indoor airflow", "Airflow",
             "Small air-side delta-T with reduced fan output.",
             ["room_temp", "inlet_temp", "fan_speed"], Severity.LOW),
    RuleSpec("R12_evap_icing", "Evaporator icing", "Airflow",
             "Coil temperature below freezing during cooling.",
             ["evap_temp", "mode"], Severity.MEDIUM),
    RuleSpec("R13_sensor_fault", "Thermistor drift/failure", "Sensors",
             "Sensor flatlined, out of range, or disagreeing with peers.",
             ["room_temp", "liquid_pipe_temp", "gas_pipe_temp"], Severity.MEDIUM),
    RuleSpec("R14_comm_error", "Communication errors", "Controls",
             "Communication fault flags or data dropouts between units.",
             ["error_code"], Severity.MEDIUM),
    RuleSpec("R15_reversing_valve", "4-way reversing valve fault", "Valves",
             "Pipe-temperature direction disagrees with commanded mode.",
             ["mode", "gas_pipe_temp", "liquid_pipe_temp"], Severity.HIGH),
    RuleSpec("R16_oil_return", "Oil return problems", "Compressor",
             "Long low-load runtime without adequate oil-return cycles.",
             ["comp_freq", "capacity_demand"], Severity.MEDIUM),
    RuleSpec("R17_high_current", "High compressor current", "Electrical",
             "Compressor current outside its frequency envelope.",
             ["comp_current", "comp_freq"], Severity.HIGH),
    RuleSpec("R18_inverter_overheat", "Inverter/heatsink overheat", "Electrical",
             "Inverter heatsink (THHS) temperature too high.",
             ["heatsink_temp"], Severity.HIGH),
    RuleSpec("R19_mode_conflict", "Simultaneous heat/cool conflict", "Controls",
             "Indoor units on one system requesting opposing modes.",
             ["mode"], Severity.LOW),
    RuleSpec("R20_part_load", "Oversizing / poor part-load behavior", "Efficiency",
             "Cycling/runtime distribution consistent with poor sizing.",
             ["comp_freq", "capacity_demand"], Severity.LOW),
    RuleSpec("R21_comfort_deviation", "Room temp overshoot/undershoot", "Comfort",
             "Room temperature deviating from setpoint for long periods.",
             ["room_temp", "set_temp"], Severity.LOW),
    RuleSpec("R22_fan_degradation", "Fan motor degradation", "Airflow",
             "Fan speed not tracking demand / abnormal fan feedback.",
             ["fan_speed", "capacity_demand"], Severity.MEDIUM),
    RuleSpec("R23_low_efficiency", "Low efficiency / COP degradation", "Efficiency",
             "Delivered-capacity proxy vs. power trending down over time.",
             ["power", "comp_freq", "outdoor_temp"], Severity.LOW),
    RuleSpec("R24_ambient_limits", "Operation outside ambient limits", "Environment",
             "Outdoor temperature outside the unit's rated envelope.",
             ["outdoor_temp", "mode"], Severity.LOW),
    RuleSpec("R25_fault_rollup", "Fault-code history rollup", "Controls",
             "Frequency and recency summary of abnormal/error codes.",
             ["error_code"], Severity.INFO),
]

CATALOG_BY_ID = {r.rule_id: r for r in CATALOG}
